POST /api/users HTTP/1.1
Content-Type: application/json
Host: localhost:3333
Content-Length: 2115

{
	"name": "luis filipe",
	"email": "teste03@gmail.com",
	"password": "senhaDeTeste",
	"atletaProfile": {
		"consultas": [
			{
				"dateTime": "2022-02-01T02:51:47.383Z",
				"codigoEspecialista": "aaf3b3d0-c836-4119-869d-0fd5e41ab31a"
			},
			{
				"dateTime": "2022-02-01T02:51:47.383Z",
				"codigoEspecialista": "df14f43f-6219-449e-ab4c-ed56e7b27533"
			}
		]
	}
}